artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUBTjC-2vf61/view?usp=share_link
  local_dir: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/feature_store

data_validation:
  root_dir: artifacts/data_validation
  input_data_dir: artifacts/data_ingestion/data
  output_data_dir: artifacts/data_validation/output